# Generated by Django 4.2.11 on 2025-05-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrecord',
            name='search_content',
        ),
        migrations.RemoveField(
            model_name='searchrecord',
            name='x',
        ),
    ]
